---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
thisfile_1 = here("data_raw", "DL_SelectFields_2023.zip")
df2023 = read_csv(thisfile_1) %>% clean_names()

thisfile_2 = here("data_raw", "DL_SelectFields_2022.zip")
df2022 = read_csv(thisfile_2) %>% clean_names

thisfile_3 = here("data_raw", "DL_SelectFields_2021.zip")
df2021 = read_csv(thisfile_3) %>% clean_names

thisfile_4 = here("data_raw", "DL_SelectFields_2020.zip")
df2020 = read_csv(thisfile_4) %>% clean_names

thisfile_5 = here("data_raw", "DL_SelectFields_2019.zip")
df2019 = read_csv(thisfile_5) %>% clean_names

thisfile_6 = here("data_raw", "DL_SelectFields_2018.zip")
df2018 = read_csv(thisfile_6) %>% clean_names

thisfile_7 = here("data_raw", "DL_SelectFields_2017.zip")
df2017 = read_csv(thisfile_7) %>% clean_names
```

```{r}
dfc=df2017 |>
bind_rows(df2018)  |>
bind_rows(df2019)  |>
bind_rows(df2020)  |>
bind_rows(df2021)  |>
bind_rows(df2022)  |>
bind_rows(df2023)
```


```{r}
dfc1=dfc  |>
  filter(passengers > 0, origin=="LGA" | dest == "LGA")
```


```{r}
dfc1 |> mutate(month_year = year + (month/12)) |> 
  ggplot(aes(month_year)) + geom_bar(aes(weight = passengers)) 
```
