---
title: 'Experiment3: More Airline data'
subtitle: Asynchronous Lecture
name: "Lucas Adams"
date: "2023-09-11"
output:
  html_document:
    df_print: paged
---



```{r}
library(tidyverse)
library(nycflights13)
library(janitor)
library(here)
```

```{r}
thisfile = here("data_raw", "DL_SelectFields.zip")

df2022 = read_csv(thisfile) %>% clean_names()
```
# Flights that had passengers and originated at LaGuardia.
```{r}
df9 = df2022 |>
  filter(passengers > 0, origin == "LGA")
```

```{r}
df9 |> 
  ggplot(aes(month)) + geom_bar()
```

```{r}
df9 |> 
  ggplot(aes(month)) + geom_bar(aes(weight = departures_performed))
```

```{r}
df9 |> 
  ggplot(aes(month)) + geom_bar(aes(weight = passengers))
```
# Departures by carrier
```{r}
df9 |> 
  ggplot(aes(month, fill =carrier_name)) + geom_bar(aes(weight = departures_performed))
```

# Flights with an origin or destination of LaGuardia.
```{r}
df10 = df2022 |> filter(passengers > 0, origin=="LGA" | dest == "LGA")
df10 |> 
  ggplot(aes(month)) + geom_bar(aes(weight = passengers))
```

# Trimming data for selected variables
```{r}
df11 = df10 |> select(month, passengers, seats, carrier_name, dest, origin)
```

```{r}
df12 = df10 |> select(1:5, month, contains("id"))
```

```{r}
df13 = df11 |> mutate(percent_loading = passengers/seats*100)
df13 |> ggplot(aes(percent_loading)) + 
  geom_histogram()+facet_wrap(~carrier_name, scales="free_y")
```

# Start of code for 9/13 Class


